language: php

php:
    - '7.1'

sudo: false

cache:
    directories:
        - $HOME/.composer/cache


before_install:
    - composer self-update

install:
    - composer install --no-progress --no-suggest --ansi

script:
    - ./vendor/bin/phpspec run --no-interaction -f dot
    - ./vendor/bin/phpunit
